---
- name: aliases
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid="{{ item.0.uuid }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
  when: item.1.value is defined

- name: multivalue aliases
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/OPNsense/Firewall/Alias/aliases/alias[@uuid="{{ item.0.uuid }}"]/{{ item.1.key }}
    value: "{{ item.1.list | join('\n') }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_alias | default([]) }}"
    - settings
  when: item.1.list is defined

...
