---

- name: dhcpd
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/dhcpd/{{ item.0.if }}/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_dhcpd | default([]) }}"
    - settings

- name: dhcpd static map
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/dhcpd/{{ item.0.if }}/staticmap[mac/text()="{{ item.0.mac }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_dhcpd_staticmap | default([]) }}"
    - settings

...
