---
- name: Count dnsservers set
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/system/dnsserver
    count: yes
  register: dnsservercount

- name: Dnsservers
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/system
    add_children: 
      - dnsserver: "{{ item }}"
    pretty_print: yes
  when: dnsservercount.count == 0
  with_items: 
    "{{ dnsserver }}"
...
