---
- name: filters
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/filter/rule[descr/text()="{{ item.0.descr }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_filter | default([]) + opn_vlan_filter | default([]) }}"
    - settings
...
