---
# example:
#
# opn_gateways:
#   - interface: WAN1
#     settings:
#       - key: gateway
#         value: 192.168.22.1
#       - key: name
#         value: GW_WAN1
#       - key: weight
#         value: 1
#       - key: ipprotocol
#         value: inet
#   - interface: WAN2
#     settings:
#       - key: gateway
#         value: 192.168.44.1
#       - key: name
#         value: GW_WAN2
#       - key: weight
#         value: 2
#       - key: ipprotocol
#         value: inet
#
# opn_gateway_groups:
#   - name: GW_WAN
#     settings:
#       - item: "GW_WAN1|1"
#       - item: "GW_WAN2|2"
#       - trigger: down
#       - descr: WAN gateway group
#

- name: gateways
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/gateways/gateway_item[interface/text()="{{ item.0.interface }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_gateways | default([]) }}"
    - settings

- name: gateway groups
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/gateways/gateway_group[name/text()="{{ item.name }}"]
    pretty_print: yes
  with_items: "{{ opn_gateway_groups | default([]) }}"

- name: gateway groups settings
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/gateways/gateway_group[name/text()="{{ item.name }}"]
    set_children: "{{ item.settings  + [ {'name':item.name } ] }}"
    pretty_print: yes
  with_items: "{{ opn_gateway_groups | default([]) }}"

...
