---
- name: general - set
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: yes
  with_dict: "{{ opn_general }}"
  when: opn_general is defined

- name: general - unset
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/{{ item }}"
    state: absent
  with_items: "{{ opn_unset }}"
  when: opn_unset is defined

...
