---
- name: interfaces - settings specific for an interface
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/interfaces/{{ item.0.interface }}/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_interfaces_specific }}"
    - settings
  when: opn_interfaces_specific is defined

- name: interfaces - settings that apply to all interfaces
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: "/opnsense/interfaces/{{ item.1 }}/{{ item.0.key }}"
    value: "{{ item.0.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_interfaces_all }}"
    - interfaces
  when: opn_interfaces_all is defined


#- name: interfaces - set vlan parent interface
#  delegate_to: localhost
#  xml:
#    path: /tmp/config-{{ inventory_hostname }}.xml
#    xpath: /opnsense/interfaces/{{ item.0.interface }}/if
#    value: "{{ opn_interfaces_vlan_parent_interface }}_vlan{{ item.0.vlan }}"
#    pretty_print: yes
#  with_subelements:
#    - "{{ opn_interfaces_specific }}"
#    - settings
#  when: opn_interfaces_specific is defined and item.0.vlan is defined

...
