---
- name: radvd
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/dhcpdv6/rule[descr/text()="{{ item.0.if }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_radvd | default([]) }}"
    - settings
...
