---

- name: sysctl - system tunables
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/sysctl/item[tunable/text()="{{ item.tunable }}"]/value
    value: "{{ item.value }}"
    pretty_print: yes
  loop: "{{ opn_sysctl }}"
  when: opn_sysctl is defined

...
