---
- name: virtualip settings that apply to all interfaces
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/virtualip/vip[vhid/text()="{{ item.1 }}"]/{{ item.0.key }}
    value: "{{ item.0.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_virtualip_all | default([]) }}"
    - vhids

- name: virtualip settings specific for a vhid
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/virtualip/vip[vhid/text()="{{ item.0.vhid }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_virtualip_specific | default([]) }}"
    - settings
...
