---

- name: OpenVPN Servers
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/openvpn/openvpn-server[vpnid/text()="{{ item.0.vpnid }}"]/{{ item.1.key }}
    value: "{{ item.1.value }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_openvpn_servers | default([])  }}"
    - settings
  when: item.1.value is defined

- name: b64 OpenVPN fields
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/openvpn/openvpn-server[vpnid/text()="{{ item.0.vpnid }}"]/{{ item.1.key }}
    value: "{{ item.1.b64_value | b64encode }}"
    pretty_print: yes
  with_subelements:
    - "{{ opn_openvpn_servers | default([]) }}"
    - settings
  when: item.1.b64_value is defined

# remove the default empty <openvpn-server/> node remains after configuring the first one

- name: OpenVPN Servers - remove default empty node
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/openvpn/openvpn-server[not(node())]
    state: absent
  when: opn_openvpn_servers is defined


...
